version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.2.1-full
    ports:
      - 82:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
  app:
    image: royceltd/apn # your docker image here e.g royceltd/royce-survey
    expose: [5055]